### ISSUE TITLE
Failure with mongoose v5.10

### ISSUE THREAD

**Issue by mryellow** [MomsFriendlyDevCo/lock#4]
Working: mongoose 5.9.29.

When updated to `5.10.0` the following error results:

```
340  const conn = _mongoose.connection;
     vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
341  return conn.openUri(uri, options, callback).then(() => _mongoose);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
342};
ERROR: conn.openUri(...).then is not a function
 ├ Mongoose.connect @ /..../node_modules/mongoose/lib/index.js +339:47
 └ SYNTAX @     at /..../node_modules/@momsfriendlydevco/lock/index.js:51 +23
```

**Comment by TeleMediaCC** [comment]
same problem.

`"mongoose": "=5.10.0"`

```
 ERROR  conn.openUri(...).then is not a function

  TypeError: conn.openUri(...).then is not a function
  at Proxy.Mongoose.connect (node_modules/mongoose/lib/index.js:339:47)
```

**Comment by mryellow** [comment]
Had a look in Mongoose and it appears a fix for a multiple-connections issue returned before promises were setup.

I imagine they'll push a hotfix before very long.

https://github.com/Automattic/mongoose/issues/9335#issuecomment-674792265

**Comment by mryellow** [comment]
I only see `lock.init()` being called once in the project where this popped up.

Which I guess means any existing connection with `this.readyState === STATES.connecting || this.readyState === STATES.connected` must effectively be a singleton from npm caching the mongoose package.

Switching to `createConnection` as per https://mongoosejs.com/docs/connections.html#multiple_connections should do the trick.

**Comment by emanual4real** [comment]
Thank God I'm not crazy!  Spent hours on this yesterday.  Downgrading from 5.10.0 to 5.9.29 has resolved my issue.

**Comment by mryellow** [comment]
Bumped the version on NPM to use `createConnection()`. Though will likely go back to using `connect()` when they fix mongoose.

**Comment by mryellow** [comment]
Mongoose `5.10.1` has a commit to patch this although not deployed to npm yet.
